//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P0006.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloFoto
    {
        public int IdCliente { get; set; }
        public int IdArtículo { get; set; }
        public int SecPhoto { get; set; }
        public byte[] FOTO { get; set; }
    }
}
