//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P0006.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBMVCEntities : DbContext
    {
        public DBMVCEntities()
            : base("name=DBMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mSTATU> mSTATUS { get; set; }
        public DbSet<TIPDOC> TIPDOCs { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public DbSet<MARCA> MARCAS { get; set; }
        public DbSet<TIPOS> TIPOS { get; set; }
    
        public virtual ObjectResult<sp_consultaCategorias_Result> sp_consultaCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaCategorias_Result>("sp_consultaCategorias");
        }
    
        public virtual ObjectResult<sp_consultaMarcas_Result> sp_consultaMarcas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaMarcas_Result>("sp_consultaMarcas");
        }
    
        public virtual ObjectResult<sp_consultaTipos_Result> sp_consultaTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaTipos_Result>("sp_consultaTipos");
        }
    
        public virtual int sp_insertaCategorias(string descripcion, byte[] imagen, ObjectParameter resultado)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertaCategorias", descripcionParameter, imagenParameter, resultado);
        }
    
        public virtual int sp_insertaMarcas(string descripcion, Nullable<bool> estatus, byte[] imagen, ObjectParameter resultado)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertaMarcas", descripcionParameter, estatusParameter, imagenParameter, resultado);
        }
    
        public virtual int sp_insertaTipos(string descripcion, byte[] imagen, ObjectParameter resultado)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertaTipos", descripcionParameter, imagenParameter, resultado);
        }
    
        public virtual int sp_ModificaCategorias(Nullable<int> idCategoria, string descripcion, Nullable<bool> estatus, byte[] imagen, ObjectParameter resultado)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCategorias", idCategoriaParameter, descripcionParameter, estatusParameter, imagenParameter, resultado);
        }
    
        public virtual int sp_ModificaMarcas(Nullable<int> idMarca, string descripcion, Nullable<bool> estatus, byte[] imagen, ObjectParameter resultado)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("IdMarca", idMarca) :
                new ObjectParameter("IdMarca", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaMarcas", idMarcaParameter, descripcionParameter, estatusParameter, imagenParameter, resultado);
        }
    
        public virtual int sp_ModificaTipos(Nullable<int> idTipo, string descripcion, Nullable<bool> estatus, byte[] imagen, ObjectParameter resultado)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaTipos", idTipoParameter, descripcionParameter, estatusParameter, imagenParameter, resultado);
        }
    }
}
